### ISSUE TITLE
Broken Pipe Exception on Parity Client

### ISSUE THREAD

**Issue by SachinSPawar** [paritytrading/parity#117]
I have a web application deployed on Tomcat 8.5.29. The web application communicates with the Parity system, running on the same machine using Parity Client. This works perfectly fine on a local setup but fails on the cloud. I am getting a Broken Pipe Exception from the Parity Client. 

```
sending data to parity server
Uhh ohh!!.. something went wrong !!
 after removing the bad connection--- null
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
	at java.nio.channels.SocketChannel.write(SocketChannel.java:502)
	at com.paritytrading.nassau.soupbintcp.SoupBinTCPSession.send(SoupBinTCPSession.java:196)
	at com.paritytrading.nassau.soupbintcp.SoupBinTCPClient.send(SoupBinTCPClient.java:118)
	at com.paritytrading.parity.pojo.ColodaxOrderEntry.send(ColodaxOrderEntry.java:180)
	at com.paritytrading.parity.client.command.WebEnterCommand.execute(WebEnterCommand.java:57)
	at com.paritytrading.parity.client.command.WebEnterCommand.execute(WebEnterCommand.java:38)
```

Is there any configuration that I am missing? 

Thanks for help in advance.

**Comment by jvirtanen** [comment]
Hi @SachinSPawar! Did you figure this one out? Based on the description, it sounds like an issue in the networking configuration in the cloud environment rather than a Parity issue.

**Comment by SachinSPawar** [comment]
@jvirtanen , The issue was due to changes we had made on top of parity client.

**Comment by jvirtanen** [comment]
Alright! Thank you for the update. 👍
