### ISSUE TITLE
simulator throwing exception/not connecting

### ISSUE THREAD

**Issue by crowlogic** [paritytrading/parity#142]
I try to run the simulator and get the message

fatal: Connection reset by peer

java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:382)
	at com.paritytrading.nassau.soupbintcp.SoupBinTCPSession.receive(SoupBinTCPSession.java:86)
	at com.paritytrading.parity.sim.Events.run(Events.java:66)
	at com.paritytrading.parity.sim.Simulator.main(Simulator.java:55)
	at com.paritytrading.parity.sim.Simulator.main(Simulator.java:26)

is there a verbose mode to debug? Is there something besides the TradingSystem process that is supposed to be running? the trading system process is running with the following config

market-data {
  session             = parity
  multicast-interface = 127.0.0.1
  multicast-group     = 224.0.0.1
  multicast-port      = 5000
  request-address     = 127.0.0.1
  request-port        = 5001
}

market-report {
  session             = parity
  multicast-interface = 127.0.0.1
  multicast-group     = 224.0.0.1
  multicast-port      = 6000
  request-address     = 127.0.0.1
  request-port        = 6001
}

order-entry {
  address = 127.0.0.1
  port    = 4000
}

instruments = [
  AAPL,
  ETH-BTC,
  EUR-USD,
]

while the simulator is running with the confi

order-entry {
  address         = 127.0.0.1
  port            = 4000
  username-prefix = FOO
  password        = sim
}

market-data {
  multicast-interface = 127.0.0.1
  multicast-group     = 224.0.0.1
  multicast-port      = 5000
  request-address     = 127.0.0.1
  request-port        = 5001
}

instrument = FOO

open {
  bid {
    price = 149.00
    size  = 1000
  }
  ask {
    price = 151.00
    size  = 1000
  }
}

# See:
#
#   T.X. Guo. An agent-based simulation of double auction markets. 2005.
#
model {
  n     = 50    # number of agents
  s     = 0.015 # mean spread
  mu    = 1     # aggregate market order rate
  delta = 0.2   # limit order decay rate
  sigma = 1000  # order size
}

**Comment by crowlogic** [comment]
I managed to get this working after resurrecting code from parity-net-0.6.0 , when I get around to it I'll put it on github
